apiVersion: apps/v1
kind: Deployment
metadata:
  name: racedevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: racedevops
  template:
    metadata:
      labels:
        app: racedevops
    spec:
      containers:
      - name: racedevops
        image: racedevopsacr.azurecr.io/racedevops:race
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "228Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: racedevops-service
spec:
  type: LoadBalancer
  selector:
    app: racedevops
  ports:
    - port: 80
      targetPort: 80
